const SUMAR_DINERO = 'SUMAR_DINERO';
const RESTAR_DINERO = 'RESTAR_DINERO';
const API_GET_POKEMONS = 'API_GET_POKEMONS';
const API_DETAIL_POKEMON = 'API_DETAIL_POKEMON'; 
const API_GET_TYPES = 'API_GET_TYPES';
const GET_ID_POKEMON = 'GET_ID_POKEMON';
const ORDER_BY_NAME = 'ORDER_BY_NAME';
const ORDER_BY_STRENGTH = 'ORDER_BY_STRENGTH';
const FILTER_BY_TYPE = 'FILTER_BY_TYPE';
const FILTER_BY_ORIGIN = 'FILTER_BY_ORIGIN';
const SET_DETAIL = 'SET_DETAIL';
const SET_POKENAME = 'SET_POKENAME';
const POST_POKEMON = 'POST_POKEMON';


export {
    POST_POKEMON,
    FILTER_BY_ORIGIN,
    FILTER_BY_TYPE,
    SET_POKENAME,
    SET_DETAIL,
    ORDER_BY_STRENGTH,
    ORDER_BY_NAME,
    GET_ID_POKEMON,
    API_GET_TYPES,
    API_GET_POKEMONS,
    SUMAR_DINERO,
    RESTAR_DINERO,
    API_DETAIL_POKEMON
}