const SUMAR_DINERO = 'SUMAR_DINERO';
const RESTAR_DINERO = 'RESTAR_DINERO';
const API_GET_POKEMONS = 'API_GET_POKEMONS';
const API_DETAIL_POKEMON = 'API_DETAIL_POKEMON'; 
const API_GET_TYPES = 'API_GET_TYPES';
const GET_ID_POKEMON = 'GET_ID_POKEMON';

export {
    GET_ID_POKEMON,
    API_GET_TYPES,
    API_GET_POKEMONS,
    SUMAR_DINERO,
    RESTAR_DINERO,
    API_DETAIL_POKEMON
}